name: World-Regain
main: eu.kingconquest.worldregain.Main
load: POSTWORLD
depend: [Vault]
softdepend: []
version: 0.0.2
author: Thomas Lundqvist
website: www.kingconquest.eu
description: World Regenerator!

commands:
  worldregain:
    description: Main Commmand
    aliases: [wr, wregain, worldr]
    permission: conquest.basic
    permission-message: You need the permission "worldregain.basic" for this command
    
permissions:
    